### ISSUE TITLE
Does not create database

### ISSUE THREAD

**Issue by sinnbeck** [lando/mssql#4]
I dont know if this is a feature request, or a bug.

When I add the mssql service, it does not seem to come with a database
```
services:
  mssql:
    type: mssql
    portforward: 1434
```
If I start it up and connect to it with the default username and password I only see the 3 default database. I would assume that it would add a database named `database`
![image](https://user-images.githubusercontent.com/13980140/161970426-1dcdc085-4c27-45a5-8b28-014ee2734800.png)

**Comment by sinnbeck** [comment]
I managed to get it working using 2 extra files and a few changed to the service. I added a folder I could map with the files needed `.lando/mssql`

configure-db.sh
```bash
#!/bin/bash

/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -d master -i /mssql/setup.sql
```
setup.sql
```sql
CREATE DATABASE $(MSSQL_DB);
```
And in .lando.yml
```
services:
  mssql:
    type: mssql
    portforward: 1434
    run_as_root:
      - /mssql/configure-db.sh
    overrides:
      volumes:
        - ./.lando/mssql:/mssql
      environment:
        MSSQL_DB: "my_database"
```

**Comment by reynoldsalec** [comment]
@sinnbeck you're correct this service doesn't create a DB, was looking at it recently for an unrelated issue and it's pretty barebones...would be nice to have it create a database that can be specified through the `creds` option just like the MySQL and MariaDB services:

```
services:
  mssql:
    type: mssql
    creds:
      database: mycooldb
      user: myuser
      password: mypassword
```
